name: Deploy
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Upload code to server
        uses: actions/checkout@v4
      - name: Installing software
        uses: actions/setup-node@v4
      - name: Installing packages
        run: npm ci
      - name: Linting
        run: npm run Lint
  Test:
    needs: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Upload code to server
        uses: actions/checkout@v4
      - name: Installing software
        uses: actions/setup-node@v4
      - name: Installing packages
        run: npm ci
      - name: testing
        run: npm run test
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Upload code to server
        uses: actions/checkout@v4
      - name: Installing software
        uses: actions/setup-node@v4
      - name: Installing packages
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying...."
      