name: Deploy
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Upload code to server
        uses: actions/checkout@v4
      - name: Installing software
        uses: actions/setup-node@v4
      - name: Installing packages
        run: npm ci
      - name: testing
        run: npm test
      